### ISSUE TITLE
Data error in "zodiaco.csv"

### ISSUE THREAD

**Issue by ziyan-c** [squillero/computer-sciences#2]
computer-sciences/Python/exams/astrologia_calciatori/zodiaco.csv

As description said there is no error in these csv files, and the dates should all in "dd/mm" format. However there are indeed some errors, such as "Libra,09/23,22/10" is in the format "mm/dd".

**Comment by squillero** [comment]
Corrected. Thx.

**Comment by ziyan-c** [comment]
Thank you Prof  :)
